name: Automatic build
on:
  push:
    branches: ["main"]
  pull_request:
    breanches: ["main"]
  # Allow run workflow manually from Action tab in Github repo's page
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3.4.1
      - name: Install project's dependencies
        run: npm install
      - name: Build client
        run: npm run build --prefix client
